### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by BetTD** [MWHunter/Grim#335]
**Describe the bug**
The server crashes when using Grim.
https://paste.sparked.host/titayiwure.txt

**To Reproduce**
Happens randomly, right when a player joins

**Server Version:**
1.17.1 (custom fork of Pufferfish)

**Grim Version (Git commit or the version in the jar's name)**
Latest beta build from Discord server

**Relevant plugins**
`
AccurateReadings*, Awita (custom plugin), BlueMap, BungeeGuard, Chunky, ChunkyBorder, Citizens, CitizensText, DeluxeMenus, Essentials, FastAsyncWorldEdit (WorldEdit), GSit, HolographicDisplays, Insights, LPC, LuckPerms, Multiverse-Core, PlaceholderAPI, ProtectionStones, ProtocolLib, spark, SuperVanish, TAB, UltimateAutoRestart, UltimateTimber, Vehicles, ViaBackwards, ViaVersion, WorldGuard
`

**Comment by MWHunter** [comment]
Fixed by https://github.com/MWHunter/Grim/commit/087761365a830755af828eef1c61441774f218bf

I'm unsure what is causing this.  I assume it's a deadlock by ViaVersion being unable to inject without getting on the main thread, and the main thread being blocked by trying to store data about a packet which relies on the injection.  I'm turning off pre and post transactions per tick to reduce spam, and to get main thread usage by default to nearly 0.  Without sending a transaction on the main thread, this shouldn't happen.

Hopefully PacketEvents can add a method to send async to avoid this in the future.

**Comment by BetTD** [comment]
Still happening sadly
https://paste.sparked.host/ibumiyejeq.txt
